app:
  dynamodb:
    # For local development with LocalStack
    # endpoint: http://localhost:4566
    endpoint: ""
    region: eu-west-1
    access-key: ""
    secret-key: ""
    table:
      tenant-info: localdev_tenant_info