server:
  port: 8048

spring:
  application:
    name: stores-service

  datasource:
    url: jdbc:postgresql://localhost:5432/store?currentSchema=store
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 50
        query:
          in_clause_parameter_padding: true
        show_sql: true
        jdbc:
          batch_size: 50

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/store?currentSchema=store

app:
  dynamodb:
    # For local development with LocalStack
    # endpoint: http://localhost:4566
    endpoint: ""
    region: eu-west-1
    access-key: ""
    secret-key: ""
    table:
      tenant-info: tenant_info

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
    enabled: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: OFF
        orm:
          jdbc:
            bind: OFF